### ISSUE TITLE
Tests Failing

### ISSUE THREAD

**Issue by wfrisby** [tokio-rs/tokio-curl#1]
The tests are failing on with armv7-unknown-linux-gnueabihf built with rustc 1.11.0 (9b21dcd6a 2016-08-15)

Below is the backtrace output:
```
(trusty)wfrisby@localhost:~/tokio-curl$ RUST_BACKTRACE=1 ./target/debug/smoke-4a2fcf2838f7784a 

running 2 tests
test download_rust_lang ... FAILED
test timeout_download_rust_lang ... FAILED

failures:

---- download_rust_lang stdout ----
	thread 'download_rust_lang' panicked at 'called `Result::unwrap()` on an `Err` value: PerformError { error: Error { repr: Custom(Custom { kind: Other, error: Error { description: "Unsupported protocol", code: 1 } }) } }', /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:788
stack backtrace:
   1: 0xb6f403b7 - std::sys::backtrace::tracing::imp::write::hbd1caa461fe9c109
   2: 0xb6f43bd7 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hdbcec33ebc315e74
   3: 0xb6f4368b - std::panicking::default_hook::h957c062fb1f730ac
   4: 0xb6f369c3 - std::panicking::rust_panic_with_hook::h7a507451d3912a00
   5: 0xb6f43e57 - std::panicking::begin_panic::h2a01de0f799786d4
   6: 0xb6f3769b - std::panicking::begin_panic_fmt::h8ced9591826d30c1
   7: 0xb6f43dfb - rust_begin_unwind
   8: 0xb6f608ef - core::panicking::panic_fmt::h9c49737ac95a342d
   9: 0xb6e52843 - core::result::unwrap_failed::h800427f2a432b8a9
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/macros.rs:29
  10: 0xb6e52667 - _<core..result..Result<T, E>>::unwrap::h22c1c37533d0b034
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libcore/result.rs:726
  11: 0xb6e36df7 - smoke::download_rust_lang::h959f009b4edb5063
                at /home/wfrisby/tokio-curl/tests/smoke.rs:45
  12: 0xb6f1cfb7 - _<F as alloc..boxed..FnBox<A>>::call_box::h09e4f01e7f04c042
  13: 0xb6f1f15f - std::panicking::try::call::h17183139b8f45741
  14: 0xb6f477df - __rust_try
  15: 0xb6f47773 - __rust_maybe_catch_panic
  16: 0xb6f1f59b - _<F as alloc..boxed..FnBox<A>>::call_box::hb5134f550ca2e6bd
  17: 0xb6f42197 - std::sys::thread::Thread::new::thread_start::h629ec84f28a75e0e

---- timeout_download_rust_lang stdout ----
	thread 'timeout_download_rust_lang' panicked at 'I/O error: [1] Unsupported protocol', tests/smoke.rs:67
stack backtrace:
   1: 0xb6f403b7 - std::sys::backtrace::tracing::imp::write::hbd1caa461fe9c109
   2: 0xb6f43bd7 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hdbcec33ebc315e74
   3: 0xb6f4368b - std::panicking::default_hook::h957c062fb1f730ac
   4: 0xb6f369c3 - std::panicking::rust_panic_with_hook::h7a507451d3912a00
   5: 0xb6f43e57 - std::panicking::begin_panic::h2a01de0f799786d4
   6: 0xb6f3769b - std::panicking::begin_panic_fmt::h8ced9591826d30c1
   7: 0xb6e55fcb - smoke::timeout_download_rust_lang::_$u7b$$u7b$closure$u7d$$u7d$::h83511cf4e2c6469e
                at /home/wfrisby/tokio-curl/<std macros>:8
   8: 0xb6e59b83 - _<futures..then..Then<A, B, F> as futures..Future>::poll::_$u7b$$u7b$closure$u7d$$u7d$::hbcc56715fcde4ad5
   9: 0xb6e571f7 - _<futures..chain..Chain<A, B, C>>::poll::hbeb5c7fc2c63565c
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.1/src/chain.rs:38
  10: 0xb6e56db7 - _<futures..then..Then<A, B, F> as futures..Future>::poll::h5ad52baef75f84cb
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.1/src/then.rs:31
  11: 0xb6e56d7f - _<futures..task..Spawn<F>>::poll_future::_$u7b$$u7b$closure$u7d$$u7d$::h420e795afbbaa334
  12: 0xb6e56d3f - _<futures..task..Spawn<T>>::enter::_$u7b$$u7b$closure$u7d$$u7d$::h81be6ac13963be70
  13: 0xb6e56cb7 - futures::task::set::_$u7b$$u7b$closure$u7d$$u7d$::h37ff7b9ae01dafee
  14: 0xb6e56c17 - _<std..thread..local..LocalKey<T>>::with::h027aafa2c6da4d77
                at /buildslave/rust-buildbot/slave/stable-dist-rustc-cross-host-linux/build/src/libstd/thread/local.rs:245
  15: 0xb6e56b1f - futures::task::set::h09aae134753844fa
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.1/src/task/mod.rs:72
  16: 0xb6e56a43 - _<futures..task..Spawn<T>>::enter::hf98dce91937c96ba
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.1/src/task/mod.rs:304
  17: 0xb6e5694b - _<futures..task..Spawn<F>>::poll_future::h9903c5bdf51a8d74
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.1/src/task/mod.rs:217
  18: 0xb6e56747 - tokio_core::reactor::Core::run::_$u7b$$u7b$closure$u7d$$u7d$::h567039e5ac767dc4
  19: 0xb6e9db57 - tokio_core::reactor::Core::_run::_$u7b$$u7b$closure$u7d$$u7d$::h10419646f66acafd
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.0/src/reactor/mod.rs:280
  20: 0xb6e9d993 - _<scoped_tls..ScopedKey<T>>::set::h77143bca7891cc28
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  21: 0xb6e99c57 - tokio_core::reactor::Core::_run::hf4b065e5636958c1
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.0/src/reactor/mod.rs:280
  22: 0xb6e5647f - tokio_core::reactor::Core::run::hd93c3c3daea92e45
                at /home/wfrisby/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.0/src/reactor/mod.rs:217
  23: 0xb6e5481b - smoke::timeout_download_rust_lang::he5ce7bc335c07ac0
                at /home/wfrisby/tokio-curl/tests/smoke.rs:71
  24: 0xb6f1cfb7 - _<F as alloc..boxed..FnBox<A>>::call_box::h09e4f01e7f04c042
  25: 0xb6f1f15f - std::panicking::try::call::h17183139b8f45741
  26: 0xb6f477df - __rust_try
  27: 0xb6f47773 - __rust_maybe_catch_panic
  28: 0xb6f1f59b - _<F as alloc..boxed..FnBox<A>>::call_box::hb5134f550ca2e6bd
  29: 0xb6f42197 - std::sys::thread::Thread::new::thread_start::h629ec84f28a75e0e


failures:
    download_rust_lang
    timeout_download_rust_lang

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured
```

**Comment by wfrisby** [comment]
Tests pass with the nightly version of rustc: 1.13.0-nightly (f1f40f850 2016-09-09)

**Comment by alexcrichton** [comment]
Thanks for the report! This looks like curl may have somehow been used without openssl support, in which case the test would fail for another reason, so no need to worry here regardless!
